import HomeBuyingProcess from "../components/buy/HomeBuyingProcess";
import MakingOfferClosing from "../components/buy/MakingOfferClosing";
import StartHomeSearch from "../components/buy/StartHomeSearch";
import SellingProcessRoadmap from "../components/sell/SellingProcessRoadmap";
import WhySellersChoose from "../components/sell/WhySellersChoose";

const homeSellingProcessData = {
  title: "Sell Your Home with Confidence",
  subtitle: "Smooth, Strategic, and Successful",
  titleClassName: "text-[30px] lg:text-[36px]",
  paragraphs: [
    "Selling your home is one of the biggest financial decisions you'll make and we're here to make it smooth, strategic, and successful.",
    "At Mike Gruosso Real Estate, we combine local market expertise with powerful marketing, personalized support, and proven selling strategies to get you the best results with less stress.",
  ],
  images: {
    primary: {
      src: "/home-beach.jpg",
      alt: "Beautiful waterfront home exterior",
    },
    secondary: {
      src: "/sold-list1.jpg",
      alt: "Recently sold home",
    },
  },
};

const freeHomeEvaluationData = {
  title: "Free Home Evaluation",
  subtitle: "Know What Your Home Is Really Worth",
  titleClassName: "text-[30px] lg:text-[36px]",
  paragraphs: [
    "Our Free Home Evaluation provides you with a true market value for your property, not just an estimate generated by an algorithm. We take the time to carefully analyze several key factors, including recent comparable sales in your area, current market trends, neighborhood demand, and the condition or upgrades of your property. This comprehensive approach ensures you receive accurate pricing insights that help maximize your profit, with no obligation and no guesswork involved.",
  ],
  backgroundImage: "/home-evaluation.avif",
  featureImage: {
    src: "/laptop-device.png",
    alt: "Home evaluation details shown on a laptop",
  },
  cta: null,
};

const sellingClosingData = {
  title: "From Offer to Closing",
  subtitle: "Selling Support Until The Final Signature",
  sectionClassName: "w-full bg-white py-20 sm:py-24",
  headingClassName: "text-[30px] lg:text-[36px]",
  formHeadingClassName: "text-[36px]",
  paragraphs: [
    "When the right offer comes in, The Gruosso Group helps you review every detail with confidence, from price and contingencies to timelines and buyer strength. We negotiate strategically to protect your goals and secure the best possible outcome.",
    "After an offer is accepted, we stay beside you through inspections, appraisal, paperwork, deadlines, and closing coordination. Our team keeps the process organized and clear so you can move forward with less stress and more confidence.",
  ],
  formTitle: "Request A Call",
};

export default function SellPage() {
  return (
    <main>
      <HomeBuyingProcess {...homeSellingProcessData} />
      <StartHomeSearch {...freeHomeEvaluationData} />
      <SellingProcessRoadmap />
      <WhySellersChoose />
      <MakingOfferClosing {...sellingClosingData} />
    </main>
  );
}
