import HomeBuyingProcess from "../components/buy/HomeBuyingProcess";
import MakingOfferClosing from "../components/buy/MakingOfferClosing";
import StartHomeSearch from "../components/buy/StartHomeSearch";
import SellingProcessRoadmap from "../components/sell/SellingProcessRoadmap";
import WhySellersChoose from "../components/sell/WhySellersChoose";

const homeSellingProcessData = {
  title: "Sell Your Home with Confidence",
  subtitle: "Smooth, Strategic, and Successful",
  titleClassName: "text-[30px] lg:text-[36px]",
  paragraphs: [
    "Selling your home is one of the biggest financial decisions you'll make and we're here to make it smooth, strategic, and successful.",
    "At Mike Gruosso Real Estate, we combine local market expertise with powerful marketing, personalized support, and proven selling strategies to get you the best results with less stress.",
  ],
  images: {
    primary: {
      src: "/sell-opportunity1.avif",
      alt: "Beautiful waterfront home exterior",
    },
    secondary: {
      src: "/sell-opportunity2.avif",
      alt: "Recently sold home",
    },
  },
};

const freeHomeEvaluationData = {
  title: "From Offer to Closing",
  subtitle: "Selling Support Until The Final Signature",
  titleClassName: "text-[30px] lg:text-[36px]",
  paragraphs: [
    "When the right offer comes in, The Gruosso Group helps you review every detail with confidence, from price and contingencies to timelines and buyer strength. We negotiate strategically to protect your goals and secure the best possible outcome.",
    "After an offer is accepted, we stay beside you through inspections, appraisal, paperwork, deadlines, and closing coordination. Our team keeps the process organized and clear so you can move forward with less stress and more confidence."
  ],
  backgroundImage: "/offer-closing.avif",
  bulletPoints: [
    "Offer terms reviewed clearly, including price, contingencies, financing strength, and closing timeline.",
    "Strategic negotiation focused on protecting your goals and improving the final outcome.",
    "Inspection, appraisal, paperwork, deadlines, and closing coordination managed with steady communication.",
    "Practical guidance at every step so you always know what matters next.",
  ],
  cta: null,
};

const sellingClosingData = {
  title: "Free Home Evaluation",
  subtitle: "Know What Your Home Is Really Worth",
  sectionClassName: "w-full bg-white pt-36 lg:pt-52 pb-10 sm:pb-14",
  stickyLeft: false,
  leftImage: { src: "/sell-img.avif", alt: "Selling your home" },
  headingClassName: "text-[30px] lg:text-[36px]",
  formHeadingClassName: "text-[36px]",
  leadFormVariant: "sell" as const,
  paragraphs: [
    "Our Free Home Evaluation provides you with a true market value for your property, not just an estimate generated by an algorithm. We take the time to carefully analyze several key factors, including recent comparable sales in your area, current market trends, neighborhood demand, and the condition or upgrades of your property. This comprehensive approach ensures you receive accurate pricing insights that help maximize your profit, with no obligation and no guesswork involved.",
    // "After an offer is accepted, we stay beside you through inspections, appraisal, paperwork, deadlines, and closing coordination. Our team keeps the process organized and clear so you can move forward with less stress and more confidence.",
  ],
};

export default function SellPage() {
  return (
    <main>
      <MakingOfferClosing {...sellingClosingData} />   
      <StartHomeSearch {...freeHomeEvaluationData} />
      <SellingProcessRoadmap />
      <WhySellersChoose />
      <HomeBuyingProcess {...homeSellingProcessData} sectionClassName="w-full bg-white pt-16 sm:pt-20 pb-24 sm:pb-32" />
    </main>
  );
}
